package com.zfoo.util.exception;

import java.io.PrintWriter;
import java.io.StringWriter;

public abstract class ExceptionUtils {

    /**
     * <p>Gets the stack trace from a Throwable as a String.</p>
     * <p>The result of this method vary by JDK version as this method uses {@link Throwable#printStackTrace(java.io.PrintWriter)}.
     *
     * @param throwable the <code>Throwable</code> to be examined
     * @return the stack trace as generated by the exception's
     */
    public static String getStackTrace(final Throwable throwable) {
        final StringWriter sw = new StringWriter();
        final PrintWriter pw = new PrintWriter(sw, true);
        throwable.printStackTrace(pw);
        return sw.getBuffer().toString();
    }

}
